// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apnmkizkuwmabhafzzjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwbm1raXprdXdtYWJoYWZ6empzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNjYzMTIsImV4cCI6MjA1OTY0MjMxMn0.m4bBUshUK0qoY-_TwslJYfbhnZwiAjHo1eEVI3Q7p5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);